### ISSUE TITLE
Create documentation using Processing docs tools

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#80]
Please help migrate documentation from Processing to Processing.R -- pick any function and add a reference page, example, and test!

Detailed instructions here:

-  https://github.com/gaocegege/Processing.R/wiki/How-to-document-Processing.R

ref https://github.com/gaocegege/Processing.R/wiki/Documentation-and-E2E-Test-Generator-Tool

**Comment by gaocegege** [comment]
@jeremydouglass Maybe we could get some docs or help from the community about how to use those tools.

**Comment by jeremydouglass** [comment]
Good idea. There are also multiple tools -- we are starting with public web documentation for beginners. Separately Processing also uses a python / XML / JavaDoc documentation build system do technical documentation.

-  https://github.com/processing/processing-docs/blob/master/java_generate/GenerateDescriptions.py

**Comment by gaocegege** [comment]
I have created a new repo: https://github.com/Processing-R/Processing.R-docs for documentation.

**Comment by gaocegege** [comment]
FMI: https://github.com/kazimuth/processing-py-site is the web reference site for processing.py

**Comment by gaocegege** [comment]
ref https://github.com/Processing-R/Processing.R-docs/commit/942edd88d376fb078bd56234baa1b6ebf5c83512

Tring to generate reference from examples/reference, although it is full of bugs.

![image](https://cloud.githubusercontent.com/assets/5100735/26785603/d5c683f4-4a35-11e7-8c4f-dcd34fd5641b.png)

**Comment by gaocegege** [comment]
I have built a tool to generate docs from `examples/reference`.

The structure of `examples/reference` should be:

```
examples/
  reference/
    <function-name>/
      .property.yml
      <function-name>1/
        <function-name>1.rpde
      <function-name>2/
      ...
```

The structure of .property.yml:

```yml
category: <category of the functino>
subcategory: <subcategory of the function>
description: <descriptinon of the function>
syntax: <syntax of the function>
parametes:
  - label: <name of the parameter>
    description: <description of the parameter>
  - ...
related:
  - <name of related function>
  - ...
```
